language: node_js
node_js:
  - "10"
  - "9"
  - "8"
cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run dev
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: www
  on:
    branch: master

