language: node_js
node_js:
  - "10"
  - "9"
  - "8"
cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run dev

deploy:
  api_key: $GITHUB_TOKEN
  provider: pages
  skip_cleanup: true
  on:
    branch: master

